[platformio]
default_envs = esp32c3-headless
src_dir = main

[env]
platform = espressif32@7.0.1
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions_n2c.csv
board_upload.flash_size = 4MB

[env:esp32c3-headless]
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.headless.defaults"

[env:esp32c3-2424s012c]
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.lcd-2424s012c.defaults"
